# -*- coding: utf-8 -*-
"""Corpus_andersen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vWlf9rQeBGizSYAZcZU9VsB-zJ0RW8H
"""

import re

import requests
from bs4 import BeautifulSoup
import pandas as pd

# Main URL of the site
main_url = "http://hca.gilead.org.il/"

# Send a request to the main URL
response = requests.get(main_url)
response.raise_for_status()  # Check if the request was successful

# Parse the main page HTML content
soup = BeautifulSoup(response.content, 'html.parser')

# Find all links on the main page
links = soup.find_all('a')

# Prepare a list to store the data
data = []

# Iterate over the links
for link in links:
    href = link.get('href')
    if href and href.endswith('.html'):
        # Construct the full URL of the book
        book_url = main_url + href

        # Send a request to the book URL
        book_response = requests.get(book_url)
        book_response.raise_for_status()

        # Parse the book page HTML content
        book_soup = BeautifulSoup(book_response.content, 'html.parser')

        # Extract the title of the book
        title = book_soup.title.string if book_soup.title else "No Title"

        # Extract the text content of the book
        paragraphs = book_soup.find_all('p')
        text = "\n".join(paragraph.get_text() for paragraph in paragraphs)

        # Append the title and text to the data list
        data.append({
            'title': title,
            'text': text
        })

# Create a pandas DataFrame from the data
df = pd.DataFrame(data)

def clean_text(text):
    text = re.sub(r'<.*?>', '', text)  # Remove HTML tags
    text = re.sub(r'[^A-Za-z0-9\s.,]+', '', text)  # Remove non-alphanumeric characters except for periods and commas
    text = re.sub(r'\s+', ' ', text).strip()  # Replace multiple spaces with a single space
    return text

df.title = df.title.apply(clean_text)
df.text = df.text.apply(clean_text)

def remove_hca(text):
    text = re.sub(r'Hans Christian Andersen', '', text)
    return text

df.title = df.title.apply(remove_hca)

df = df.drop(index = [i for i in range(9)])

df.to_excel('HansChristianAndersen.xlsx', index = False)