# -*- coding: utf-8 -*-
"""Corpus_grimm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSBMgdhIFOvf4KjgEURaSSTgUcY9GsyO
"""

import pandas as pd
import requests

df = pd.read_excel("Corpus_grimm.xlsx")

def create_indexes(x):
    list_of_indexes = []
    for i in range(1,x):
        if i < 10:
            list_of_indexes.append("00"+str(i))
        elif i < 100:
            list_of_indexes.append("0"+str(i))
        else:
            list_of_indexes.append(str(i))
    return list_of_indexes

def download_txt_file(index):
    url = "https://www.cs.cmu.edu/~spok/grimmtmp/" + index + ".txt"
    response = requests.get(url)
    return response

test = download_txt_file('001')
test.text

len(df)

indexes = create_indexes(len(df)+1)
list_of_texts = []
for i in indexes:
        text = download_txt_file(i)
        print('downloaded ' + str(i))
        list_of_texts.append(text.text)

for i in range(len(df)):
    df.Text.iloc[i] = list_of_texts[i]

df.to_excel('Corpus_grimm_with_text.xlsx')

df.head()



